# Generated by Django 6.0.6 on 2026-07-30 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0003_remove_commandcategory_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinuxCommandCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Linux Command Categories',
            },
        ),
        migrations.CreateModel(
            name='LinuxCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('command', models.CharField(max_length=200)),
                ('position', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='command_screenshots/%Y/%m/')),
                ('command_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set+', to='common.commandcategory')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='linux_commands.linuxcommandcategory')),
            ],
            options={
                'ordering': ['position'],
                'abstract': False,
            },
        ),
    ]
