# Generated by Django 6.0.6 on 2026-09-28 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attacks', '0014_attackcommandelement'),
        ('common', '0003_remove_commandcategory_order'),
        ('linux_commands', '0002_linuxcommandcontentblock'),
        ('tools', '0010_swap_command_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinuxCommandElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('element_type', models.CharField(choices=[('title', 'Title'), ('description', 'Description'), ('command', 'Command'), ('image', 'Image'), ('link', 'Link')], max_length=20)),
                ('text', models.CharField(blank=True, max_length=200)),
                ('description_text', models.TextField(blank=True)),
                ('command_text', models.CharField(blank=True, max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to='command_element_images/%Y/%m/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='linux_commands.linuxcommandcategory')),
                ('command_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='common.commandcategory')),
                ('link_attack', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='attacks.attack')),
                ('link_tool', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tools.tool')),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
    ]
