# Generated by Django 6.0.6 on 2026-09-28 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linux_commands', '0004_flatten_content_blocks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linuxcommandelement',
            name='element_type',
            field=models.CharField(blank=True, choices=[('title', 'Title'), ('description', 'Description'), ('command', 'Command'), ('image', 'Image'), ('link', 'Link')], max_length=20),
        ),
    ]
