# Generated by Django 6.0.6 on 2026-09-28 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linux_commands', '0009_alter_linuxcommandelement_command_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linuxcommandcontentblock',
            name='category',
        ),
        migrations.RemoveField(
            model_name='linuxcommandcontentblock',
            name='related_attack',
        ),
        migrations.RemoveField(
            model_name='linuxcommandcontentblock',
            name='related_tool',
        ),
        migrations.DeleteModel(
            name='LinuxCommand',
        ),
        migrations.DeleteModel(
            name='LinuxCommandContentBlock',
        ),
    ]
