# Generated by Django 6.0.6 on 2026-08-21 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attacks', '0007_attackcommand_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Port Categories',
            },
        ),
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('service_name', models.CharField(max_length=100)),
                ('purpose', models.CharField(max_length=300)),
                ('vulnerability', models.TextField()),
                ('related_attack', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='attacks.attack')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ports', to='ports.portcategory')),
            ],
        ),
    ]
