# Generated by Django 6.0.6 on 2026-08-21 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ports', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='port',
            options={'ordering': ['number']},
        ),
    ]
