# Generated by Django 6.0.6 on 2026-08-21 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ports', '0002_alter_port_options'),
        ('tools', '0007_toolcommand_image_alter_toolcommand_command_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='port',
            name='related_tool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tools.tool'),
        ),
    ]
