# Generated by Django 6.0.6 on 2026-08-21 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ports', '0003_port_related_tool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='port',
            name='number',
            field=models.CharField(max_length=20),
        ),
    ]
