# Generated by Django 6.0.6 on 2026-09-24 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attacks', '0013_content_block_sortable'),
        ('ports', '0004_alter_port_number'),
        ('tools', '0010_swap_command_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='port_block_images/%Y/%m/')),
                ('button_label', models.CharField(blank=True, max_length=100)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks', to='ports.portcategory')),
                ('related_attack', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_from_port_blocks', to='attacks.attack')),
                ('related_tool', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_from_port_blocks', to='tools.tool')),
            ],
            options={
                'verbose_name': 'Content Block',
                'verbose_name_plural': 'Content Blocks',
                'ordering': ['order'],
            },
        ),
    ]
