# Generated by Django 6.0.6 on 2026-07-25 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandcategory',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
