# Generated by Django 6.0.6 on 2026-07-26 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_commandcategory_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commandcategory',
            name='order',
        ),
    ]
