# Generated by Django 6.0.6 on 2026-07-17 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attacks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attackcategory',
            options={'verbose_name_plural': 'Attack Categories'},
        ),
        migrations.RemoveField(
            model_name='attack',
            name='usage',
        ),
        migrations.AlterField(
            model_name='attack',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='attacks.attackcategory'),
        ),
        migrations.CreateModel(
            name='AttackCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('command', models.CharField(max_length=200)),
                ('attack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='attacks.attack')),
            ],
        ),
    ]
