# Generated by Django 6.0.6 on 2026-07-17 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attacks', '0002_alter_attackcategory_options_remove_attack_usage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attack',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attacks', to='attacks.attackcategory'),
        ),
    ]
