# Generated by Django 6.0.6 on 2026-07-25 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attacks', '0004_attack_created_at'),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attackcommand',
            name='command_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attack_commands', to='common.commandcategory'),
        ),
    ]
