# Generated by Django 6.0.6 on 2026-07-26 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attacks', '0005_attackcommand_command_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attackcommand',
            options={'ordering': ['position']},
        ),
        migrations.AddField(
            model_name='attackcommand',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
