# Generated by Django 6.0.6 on 2026-07-26 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attacks', '0006_alter_attackcommand_options_attackcommand_position'),
        ('common', '0003_remove_commandcategory_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='attackcommand',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='command_screenshots/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='attackcommand',
            name='command_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set+', to='common.commandcategory'),
        ),
    ]
