# Generated by Django 6.0.6 on 2026-09-24 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attacks', '0007_attackcommand_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttackCommandCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='category_images/%Y/%m/')),
                ('button_label', models.CharField(blank=True, max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('attack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='command_categories', to='attacks.attack')),
                ('related_attack', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_from_categories', to='attacks.attack')),
            ],
            options={
                'verbose_name_plural': 'Attack Command Categories',
                'ordering': ['attack', 'order'],
                'unique_together': {('attack', 'name')},
            },
        ),
        migrations.AddField(
            model_name='attackcommand',
            name='new_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commands', to='attacks.attackcommandcategory'),
        ),
    ]
