# Generated by Django 6.0.6 on 2026-09-24 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attacks', '0010_swap_command_category'),
        ('tools', '0007_toolcommand_image_alter_toolcommand_command_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='attackcommandcategory',
            name='related_tool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_from_attack_categories', to='tools.tool'),
        ),
    ]
