# Generated by Django 6.0.6 on 2026-09-24 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attacks', '0012_seed_hardcoded_blocks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attackcommandcategory',
            options={'ordering': ['order'], 'verbose_name': 'Content Block', 'verbose_name_plural': 'Content Blocks'},
        ),
        migrations.AlterUniqueTogether(
            name='attackcommandcategory',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='attackcommandcategory',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='attackcommandcategory',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
