# Generated by Django 6.0.6 on 2026-09-28 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attacks', '0016_alter_attackcommandelement_element_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attackcommandelement',
            name='text',
            field=models.CharField(blank=True, max_length=200, verbose_name='Name'),
        ),
    ]
