# Generated by Django 6.0.6 on 2026-09-28 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attacks', '0019_move_command_descriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attackcommandelement',
            name='command_description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
    ]
