# Generated by Django 6.0.6 on 2026-09-28 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attacks', '0020_alter_attackcommandelement_command_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attackcommandcategory',
            name='attack',
        ),
        migrations.RemoveField(
            model_name='attackcommandcategory',
            name='related_attack',
        ),
        migrations.RemoveField(
            model_name='attackcommandcategory',
            name='related_tool',
        ),
        migrations.DeleteModel(
            name='AttackCommand',
        ),
        migrations.DeleteModel(
            name='AttackCommandCategory',
        ),
    ]
