# Generated by Django 6.0.6 on 2026-07-17 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='toolcategory',
            options={'verbose_name_plural': 'Tool Categories'},
        ),
        migrations.RemoveField(
            model_name='tool',
            name='usage',
        ),
        migrations.AlterField(
            model_name='tool',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tools.toolcategory'),
        ),
        migrations.CreateModel(
            name='ToolCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('command', models.CharField(max_length=200)),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='tools.tool')),
            ],
        ),
    ]
