# Generated by Django 6.0.6 on 2026-07-17 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_alter_toolcategory_options_remove_tool_usage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tools', to='tools.toolcategory'),
        ),
    ]
