# Generated by Django 6.0.6 on 2026-07-24 12:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0003_alter_tool_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 7, 24, 12, 38, 32, 140714, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
