# Generated by Django 6.0.6 on 2026-07-25 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('tools', '0004_tool_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolcommand',
            name='command_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tool_commands', to='common.commandcategory'),
        ),
    ]
