# Generated by Django 6.0.6 on 2026-09-24 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attacks', '0013_content_block_sortable'),
        ('tools', '0007_toolcommand_image_alter_toolcommand_command_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='tool_block_images/%Y/%m/')),
                ('button_label', models.CharField(blank=True, max_length=100)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('related_attack', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_from_tool_blocks', to='attacks.attack')),
                ('related_tool', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_from_tool_blocks', to='tools.tool')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks', to='tools.tool')),
            ],
            options={
                'verbose_name': 'Content Block',
                'verbose_name_plural': 'Content Blocks',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='toolcommand',
            name='new_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commands', to='tools.toolcontentblock'),
        ),
    ]
