# Generated by Django 6.0.6 on 2026-09-28 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0017_alter_toolcommandelement_command_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toolcontentblock',
            name='related_attack',
        ),
        migrations.RemoveField(
            model_name='toolcontentblock',
            name='related_tool',
        ),
        migrations.RemoveField(
            model_name='toolcontentblock',
            name='tool',
        ),
        migrations.DeleteModel(
            name='ToolCommand',
        ),
        migrations.DeleteModel(
            name='ToolContentBlock',
        ),
    ]
