# Generated by Django 6.0.6 on 2026-09-28 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0018_remove_toolcontentblock_related_attack_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toolcommandelement',
            name='link_attack',
        ),
        migrations.RemoveField(
            model_name='toolcommandelement',
            name='link_tool',
        ),
        migrations.AlterField(
            model_name='toolcommandelement',
            name='element_type',
            field=models.CharField(blank=True, choices=[('title', 'Title'), ('description', 'Description'), ('command', 'Command'), ('image', 'Image')], max_length=20),
        ),
    ]
