# Generated by Django 6.0.6 on 2026-09-28 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0019_remove_toolcommandelement_link_attack_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolCommandElementImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='command_element_images/%Y/%m/')),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='tools.toolcommandelement')),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
    ]
